site_name: FiberArt 参考文档
theme:
  name: material
  language: zh
  logo: images/logo.svg
  features:
    - navigation.path
    - toc.integrate
    - toc.follow
    - navigation.footer

copyright: Copyright © 2022 - 2024 FiberArt


nav:
  - 主页: index.md
  - 快速上手: getting_started.md
  - 规划参数: plan_parameters.md
  - 规划器: ply_planner.md
  - 全局参数: global_parameters.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - attr_list
      

extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:fiberart@duck.com

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

plugins:
  - offline