site_name: FiberArt 参考文档
theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.emoji
      